server:
  port: 1313
spring:
  sql:
   init:
    mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  main:
    lazy-initialization: true
  mvc:
    servlet:
      path: /api
  jackson:
    date-format: yyyy-MM-dd
jwt:
  secretKey: SupperKey
  expireTime: 864000000

